from multiprocessing import connection

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, DeclarativeBase


DATABASE_URL = "sqlite:///./book.db"

# creates a db connection and a session factory for the application to use. The `echo=True` parameter will log all SQL statements generated by SQLAlchemy, which can be helpful for debugging.
engine = create_engine(DATABASE_URL, echo=True)

# he `sessionLocal` variable is a session factory that can be used to create new database sessions when needed.
sessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


# T The `Base` class is a declarative base class that can be used to define the database models.
class Base(DeclarativeBase):
    pass
